name: Integration

on: [push]

jobs:
  chore:
    name: Testing
    runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@master

    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        version: 12.x
        
    - name: Use Yarn
      run: |
        npm install -g yarn
    
    - name: Install
      run: |
        yarn
    
    - name: Build
      run: |
        yarn build
    
    - name: Test
      run: |
        yarn test
