name: 'GraphQL Inspector'
author: 'Kamil Kisiela <kamil.kisiela@gmail.com>'
description: 'Tooling for GraphQL. Compare schemas, find breaking changes, find similar types.'
branding:
  icon: 'search'
  color: 'orange'
inputs:
  schema:
    description: 'Ref and Path to GraphQL Schema (e.g. "master:schema.graphql")'
    required: true
  github-token:
    description: 'Github Token'
outputs:
  changes:
    description: 'Total number of changes'
runs:
  using: 'node12'
  main: 'action/index.js'
