[build]
  Command = "(cd website/live && yarn install) && yarn build:netlify"
  Functions = "dist/functions"
  Publish = "website/build/graphql-inspector"

[[redirects]]
  from = "/install"
  to = "https://github.com/apps/graphql-inspector"
  status = 301
  force = false
