packages:
  - "packages/*"
  - "packages/action/*"
  - "packages/ci/*"
  - "packages/cli/*"
  - "packages/config/*"
  - "packages/core/*"
  - "packages/github/*"
  - "packages/logger/*"
  - "packages/testing/*"
  - "packages/commands/*"
  - "packages/commands/audit/*"
  - "packages/commands/coverage/*"
  - "packages/commands/diff/*"
  - "packages/commands/docs/*"
  - "packages/commands/introspect/*"
  - "packages/commands/serve/*"
  - "packages/commands/similar/*"
  - "packages/commands/validate/*"
  - "packages/loaders/*"
  - "packages/loaders/code/*"
  - "packages/loaders/git/*"
  - "packages/loaders/github/*"
  - "packages/loaders/graphql/*"
  - "packages/loaders/json/*"
  - "packages/loaders/url/*"
  - website
