name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20, 22, 23]
    env:
      CI: true

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Get pnpm cache - Set output
        id: pnpm-cache
        run: echo "{dir}={pnpm cache dir}" >> $GITHUB_OUTPUT

      - name: Cache pnpm
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ${ env.dir }
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install
        run: pnpm i --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Lint ESLint
        run: pnpm lint

      - name: Lint Prettier
        run: pnpm lint:prettier

      - name: Integration tests
        run: |
          chmod +x ./packages/cli/dist/cjs/index.js

          echo 2001
          node ./packages/cli/dist/cjs/index.js validate './integration_tests/2001/operations/**/*.graphql' './integration_tests/2001/schema.graphql'

          echo 1991
          node ./packages/cli/dist/cjs/index.js validate './integration_tests/1991/two-operations.js' './integration_tests/1991/schema.graphql'

          echo 1985
          node ./packages/cli/dist/cjs/index.js introspect ./integration_tests/1985/schema.js || echo 'TODO'

          echo 2108
          node ./packages/cli/dist/cjs/index.js introspect './integration_tests/2108/**/!(excluded)/*.graphql' --write ./2108.graphql
            if grep -ic "bar" ./2108.graphql
            then echo "Broken" && exit 1
            else echo "Works"
            fi

          echo 2027
          node ./packages/cli/dist/cjs/index.js diff ./integration_tests/2027/schema-before.graphql ./integration_tests/2027/schema-after.graphql --rule considerUsage --onUsage ./integration_tests/2027/unused-hotels.js

          echo 2088
          node ./packages/cli/dist/cjs/index.js diff ./integration_tests/2088/old.graphql ./integration_tests/2088/new.graphql --rule suppressRemovalOfDeprecatedField
