name: pr

on:
  pull_request:
    branches:
      - master

jobs:
  algolia:
    uses: the-guild-org/shared-config/.github/workflows/algolia-integrity.yml@main
    with:
      domain: https://www.the-guild.dev/graphql/inspector/
      source: 'Inspector'
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
