name: Test Action

on: [push, pull_request]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: feat/rules-in-action-diff
        with:
          schema: "master:schema.graphql"
