name: Test Action

on: [push, pull_request, fork]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: .
        with:
          schema: "master:schema.graphql"
