name: Test Action

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: rules-in-action-diff
        with:
          schema: "master:schema.graphql"
