name: Website	
on: 	
  push:	
    branches:	
      - master
jobs:	
  Deploy:	
    name: Deploy website	
    runs-on: ubuntu-latest	
    steps:	
      - name: Checkout
        uses: actions/checkout@v2	

      - name: Use Node.js 14
        uses: actions/setup-node@v1	
        with:	
          node-version: 14

      - name: Vercel Deployment	
        uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}	
          vercel-args: '--prod'
          vercel-project-name: 'GraphQL Inspector'
          vercel-project-id: ${{ secrets.ZEIT_PROJECT }}
          vercel-org-id: ${{ secrets.ZEIT_ORG }}

      - name: Index Docs
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          file: algolia/config.json
