name: Website	
on: 	
  push:	
    branches:	
      - master
jobs:	
  Deploy:	
    name: Deploy website	
    runs-on: ubuntu-latest	
    steps:	
      - name: Checkout
        uses: actions/checkout@v2	

      - name: Use Node.js 14
        uses: actions/setup-node@v2	
        with:	
          node-version: 14

      - name: Index Docs
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          file: algolia/config.json
